language: cpp

os:
  - osx

compiler:
  - gcc
  - clang

branches:
  only:
    - osx_test_debug

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install libmodbus libmicrohttpd; fi

script: 
  - mkdir build && cd build && cmake -DFULL=ON ..
  - make
  #- make package #can turn this on when we do a deploy step
  - build/ODC_tests
  #- build/DNP3Port_tests #opendnp3 bug makes this hang at the moment
  - build/MD3Port_tests
  
